name: Rust

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

permissions: write-all

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cargo fmt --all -- --check
  lint:
    needs: [format]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cargo clippy --all-targets --all-features -- -D clippy::pedantic
  test:
    needs: [format, lint]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            os: windows-latest
          - target: x86_64-apple-darwin
            os: macos-lastest
          - target: aarch64-apple-darwin
            os: macos-lastest
          - target: x86_64-unknown-linux-musl
            os: ubuntu-lastest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            #rustup target add aarch64-apple-darwin
    steps:
    - uses: actions/checkout@v3
    - run: cargo test --verbose --all --target=${{ matrix.target }}
  build:
    needs: [format, lint]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            os: windows-latest
          - target: x86_64-apple-darwin
            os: macos-lastest
          - target: aarch64-apple-darwin
            os: macos-lastest
          - target: x86_64-unknown-linux-musl
            os: ubuntu-lastest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - if: "!startsWith(github.ref, 'refs/tags/')"
      run: cargo build --verbose --target=${{ matrix.target }}
    - if: startsWith(github.ref, 'refs/tags/')
      run: cargo build --release --target=${{ matrix.target }}
    - if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v3
      with:
        name: tfexe_${{ matrix.target }}
        path: target/${{ matrix.target }}/release/tfexe
  release:
    needs: [format, lint, test, build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-apple-darwin, aarch64-apple-darwin, x86_64-unknown-linux-musl, aarch64-unknown-linux-gnu]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: tfexe_${{ matrix.target }}
        path: tfexe_${{ matrix.target }}
    - run: gh release create ${GITHUB_REF#refs/*/} --generate-notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: gh release upload ${GITHUB_REF#refs/*/} tfexe_${{ matrix.target }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

