name: Tests

on:
  push:
    branches:
      - main
    paths:
      - '**.rs'
      - '**.toml'
      - '.github/workflows/tests.yml'
    tags:
      - '*'
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  tfexe:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: opentofu/setup-opentofu@v1
    - uses: opentofu/setup-opentofu@v1.0
    - uses: opentofu/setup-opentofu@v1.0.0
