name: Tests

on:
  push:
    branches:
      - main
    paths:
      - '**.rs'
      - '**.toml'
      - '.github/workflows/tests.yml'
    tags:
      - '*'
  pull_request:
    branches:
      - main

permissions: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  tfexe:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        #os: [ubuntu-latest, macos-latest]
        project: [project1, project2, project4]
        tfexe: [terraform, tofu, tfswitch]
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
    - uses: opentofu/setup-opentofu@v1
    - if: ${{ matrix.tfexe == 'tfswitch' }}
      run: curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | sudo bash
    - run: cargo run -- init
      working-directory: ./test_dir/${{ matrix.project }}/
      env:
        TFEXE: ${{ matrix.tfexe }}
